### ISSUE TITLE
Description and example of vmlaq_n_f64 does not match its signature in arm_neon.h

### ISSUE THREAD

**Issue by lml108** [thenifty/neon-guide#1]
The description and example of vmlaq_n_f64 given in neon guide does not match signature of vmlaq_n_f64 in arm_neon.h
The signature in arm_neon.h file is 
vmlaq_n_f64 (float64x2_t a, float64x2_t b, float64_t c)

So the last parameter is a scalar. But in the example given in neon guide, the 3rd argument used is a vector and not a scalar.

**Comment by aledalgrande** [comment]
Good catch! `vmlaq_n_f64` was actually explained below, and that was the example for `vmlaq_f32` instead.

Thanks
