### ISSUE TITLE
Will more intrinsics be given here?

### ISSUE THREAD

**Issue by openluopworld** [thenifty/neon-guide#2]
This is better for understanding. So will more intrinsics be added? Thanks

**Comment by aledalgrande** [comment]
Sure, which ones do you need?

**Comment by openluopworld** [comment]
Thanks for your reply.
1) I mainly focus on cryptography, so some logical operations (such as _vtrn_ and _vsli_) are needed now.
2) Since most of the resources on the internet just give a brief description, I will feel very happy if you can offer some references. And then I can learn by myself.

Thanks so much for your help.

**Comment by openluopworld** [comment]
Found an tool http://szeged.github.io/nevada/ helpful for understanding.
